import { test, expect } from '@playwright/test';

test('Verify login with valid credentials', async ({ page }) => {
await page.goto("https://demoqa.com/automation-practice-form")
await page.locator("(//li[@id='item-0']//span)[2]").click()
await page.locator("").fill('Ravi')
await page.locator("//input[@id='userEmail']").fill("ravi@123.com")
await page.locator("label[for='gender-radio-2']").click()
await page.locator("//input[@id='userNumber']").fill("9876543210")
await page.locator("//input[@id='dateOfBirthInput']").click()
await page.locator("//select[@class='react-datepicker__month-select']").selectOption("4")
await page.locator("//select[@class='react-datepicker__year-select']").selectOption("1990")
await page.locator("(//div[@class='react-datepicker__day react-datepicker__day--015'])[2]").click()
await page.locator("//input[@id='subjectsInput']").fill("Maths")
await page.locator("//div[@id='subjectsContainer']").press('Enter')
await page.locator("label[for='hobbies-checkbox-1']").click()
await page.locator("//input[@id='uploadPicture']").setInputFiles("C:/Users/Ravi/OneDrive/Pictures/Saved Pictures/download (1).jpg")
await page.locator("//textarea[@id='currentAddress']").fill("Pune")
await page.locator("//select[@id='state']").click()
await page.locator("//div[@id='state']//div[2]").click()
await page.locator("//select[@id='city']").click()
await page.locator("//div[@id='city']//div[2]").click()
await page.locator("//button[@id='submit']").click()
})
